version: '3.8'

services:
  scraperr:
    image: jpyles0524/scraperr:latest
    container_name: scraperr
    command: ["npm","run","start"]
    environment:
      - NEXT_PUBLIC_API_URL=http://scraperr_api:8000
      - SERVER_URL=http://scraperr_api:8000
    ports:
      - "80:3000"
    networks:
      - web

  scraperr_api:
    init: true
    image: jpyles0524/scraperr_api:latest
    container_name: scraperr_api
    environment:
      - LOG_LEVEL=INFO
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=600
    ports:
      - "8000:8000"
    volumes:
      - ./data:/project/app/data
      - ./media:/project/app/media
    networks:
      - web

networks:
  web: